const domainName = "http://35.174.163.245:4000"

export const urls = {
  forgetPassword: `${domainName}/user/forget-password`,
  resetPassword: `${domainName}/user/reset-password`,
  setPassword: `${domainName}/user/set-password`,
  login: `${domainName}/user/login`,
  register: `${domainName}/user/register`,
  userData: `${domainName}/user/user-data`,
  userLogout: `${domainName}/user/user-logout`,
  allCategories: `${domainName}/get-all-category`,
  singleCategory: `${domainName}/get-single-category`,
  allItems: `${domainName}/get-all-items`,
  currentOrderDetails: `${domainName}/order/current-order-details`,
  allPastOrders: `${domainName}/order/all-past-orders`,
  ItemDetails: `${domainName}/get-item-details`,
  allFoodItems: `${domainName}/all-food-items`,
  allPopularFoodItem: `${domainName}/admin/menu-editor/popular-food-item`,
  singleOrder: `${domainName}/order/get-single-order`,
  wishlist: `${domainName}/user/all-wishlist-items`,
  getIncompleteOrder: `${domainName}/order/incomplete-orders`,
  restaurantOpenStatus: `${domainName}/get-restaurant-open-status`,
  addNewOrder: `${domainName}/order/add-new-order`,
  updateUserDetails: `${domainName}/user/update-user-details`,
  incompleteOrder: `${domainName}/order/incomplete-order`,
  addToWishlist: `${domainName}/user/add-wishlist-food-items`,
  deleteIncompleteOrder: `${domainName}/order/delete-incomplete-order`,
  deleteWishlistFood: `${domainName}/user/delete-wishlisted-food`,
};
